### PR TITLE
Fix file leak when running in Docker

### PR DESCRIPTION
**Pull request by codetheweb**
Closes https://github.com/codetheweb/muse/issues/966.

- [ ] I updated the changelog

### CODE REVIEW

**Comment by GitGurky** [comment]
is this in the masterbuild? I notice in unraid my ram usage just slowly keeps creeping up the longer I listen to the bot.

**Comment by codetheweb** [comment]
This was superseeded by https://github.com/codetheweb/muse/pull/976. It looks like the issue should be fixed when running in Docker, but may not yet be fixed if you're running it manually from the repo. How do you run Muse?

**Comment by GitGurky** [comment]
Its from the unraid docker. I will give it a few more tests when I have some time.

**Comment by FoxxMD** [comment]
[Unraid CA for muse](https://github.com/wupasscat/unraid-templates/blob/main/muse/muse.xml#L4) is using the official codetheweb/muse docker image, just FYI

**Pull request closed without merging**
