### PR TITLE
Implement volume control #830

### LINKED ISSUE #830: Enhancement: Volume control
I love the project, however we cannot use it in our setup because there is no volume control. Is there a chance it will be added in the future?
We use Discord with a listening bot to make the audio available on a speaker system using a Raspberry Pi, however we cannot access the volume from there easily.

### PR DESCRIPTION
**Pull request by FoxxMD**
* Enabled using env VOLUME_CONTROL=true
* Disabled by default

Closes #830

### CODE REVIEW

**Comment by FoxxMD** [comment]
Er...need to make volume persistent first. Please hold.

**Review by codetheweb — COMMENTED** [review]
thanks for the contribution!

1. let's remove the `VOLUME_CONTROL` env var, I think this command can just always be available
2. we should persist this in the sqlite database so volume changes survive across Muse restarts

**Comment by FoxxMD** [comment]
`VOLUME_CONTROL` was implemented because in the original issue you cited volume control as having the potential to be abused, which I agree with. Right now, even w/o the env, only guild admins can use the control. 

Would you prefer to keep it this way? I'd prefer to make it accessible to admin and role-based so admins can dole out control to trusted users. I have no problem implementing that if that is ok for you.

For settings in sqlite -- I see that currently each setting is a different column. I usually prefer to do a KV approach so that new settings can be added without requiring a migration. Would that be acceptable? I'll write the migrations for that as well.

**Review by codetheweb — COMMENTED** [review]
sorry for my late reply, let's keep the existing structure of the config table and add a new column (I prefer the existing approach because it's more conventional and allows for correct data types instead of each setting being a string)

otherwise looks good!

**Review by codetheweb — COMMENTED** [review]
made a few minor changes and it's working great, only comment is that changes to the setting don't take effect until after Muse is started; is it possible to reload the config on the fly?

**Review by FoxxMD — COMMENTED** [review]
I believe this change should address using newest default volume. Sets default vol on new class field and uses that if volume is not explicitly set for the player. This way the player will always get most up-to-date default volume and use it if no user interacts with `/volume` command.

**Comment by codetheweb** [comment]
looks like there's some merge conflicts, happy to take a final look and merge after they're resolved

@GitGurky in the meantime, if you're using the Docker image, feel free to switch to the image tag that the bot posted above to start using this

**Comment by FoxxMD** [comment]
This is ready to merge, again.

@GitGurky you should use [`foxxmd/muse:latest`](https://hub.docker.com/layers/foxxmd/muse/latest/images/sha256-6c59c196b4c6d50c58adb10c6f1f56ed668d745569543b81b922888f97a1220b?context=explore) because its the latest code IE this PR merged with latest muse. `codetheweb/muse:pr-994` is the PR as of feb 2 which is missing features and not up to date with db migrations.

**Comment by codetheweb** [comment]
> codetheweb/muse:pr-994 is the PR as of feb 2 which is missing features and not up to date with db migrations.

hmm, why do you say that? going by the commit hash it seems to have the latest commit

**Review by codetheweb — APPROVED** [review]
seems to be working great!

**Pull request merged**
