### PR TITLE
Fix case-sensitive import warning

### LINKED ISSUE #614: Start errors
**What's happening?**
Trying to install this bot on my raspberry pi server.

**Logs**

```
> muse@1.8.2 start
> npm run env:set-database-url -- esmo src/scripts/migrate-and-start.ts


> muse@1.8.2 env:set-database-url
> esmo src/scripts/run-with-database-url.ts "esmo" "src/scripts/migrate-and-start.ts"

(node:21536) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21536) DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: getFormat, transformSource
(node:21574) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21574) DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: getFormat, transformSource
▲ [WARNING] Use "node_modules/youtube.ts/dist/Youtube.js" instead of "node_modules/youtube.ts/dist/youtube.js" to avoid issues with case-sensitive file systems

    <stdin>:1:7:
      1 │ import "youtube.ts/dist/youtube.js"
        ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/opt/muse/node_modules/youtube.ts/dist/youtube.js' imported from /opt/muse/src/services/third-party.ts
    at new NodeError (node:internal/errors:371:5)
    at finalizeResolution (node:internal/modules/esm/resolve:418:11)
    at moduleResolve (node:internal/modules/esm/resolve:983:10)
    at defaultResolve (node:internal/modules/esm/resolve:1080:11)
    at resolve (file:///opt/muse/node_modules/esbuild-node-loader/loader.mjs:126:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ESMLoader.resolve (node:internal/modules/esm/loader:530:24)
    at async ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:7)
    at async ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:81:21)
    at async Promise.all (index 2) {
  code: 'ERR_MODULE_NOT_FOUND'
}
file:///opt/muse/node_modules/execa/lib/error.js:59
                error = new Error(message);
                        ^

Error: Command failed with exit code 1: esmo src/scripts/migrate-and-start.ts
    at makeError (file:///opt/muse/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///opt/muse/node_modules/execa/index.js:119:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///opt/muse/src/scripts/run-with-database-url.ts:5:3 {
  shortMessage: 'Command failed with exit code 1: esmo src/scripts/migrate-and-start.ts',
  command: 'esmo src/scripts/migrate-and-start.ts',
  escapedCommand: 'esmo "src/scripts/migrate-and-start.ts"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Runtime**
I'm running Muse:
- [x] Directly from the cloned repository
- [ ] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: latest commit
- Docker (if applicable):
- OS: Raspberry Pi OS Lite (64 bit)

### PR DESCRIPTION
**Pull request by pierluigizagaria**
Closes #614 

Fixed import warning causing crash on Raspberry Pi OS (x64).

### CODE REVIEW

**Comment by codetheweb** [comment]
Thanks! Can you take a look at the type issue?

**Comment by pierluigizagaria** [comment]
I could't get this error on my machine. Tried with `yarn tsc` but everything is fine

**Comment by pierluigizagaria** [comment]
It's a still going on issue https://github.com/microsoft/TypeScript/issues/21736

**Comment by codetheweb** [comment]
I guess I'm not sure why it was importing from `dist/` in the first place.

Could you try the latest and see if that works for you?

**Comment by codetheweb** [comment]
Never mind, I see why. 😛 

Let's see what happens in https://github.com/Tenpi/youtube.ts/issues/21.

**Pull request merged**
