### PR TITLE
Better file caching

### PR DESCRIPTION
**Pull request by codetheweb**
Closes https://github.com/codetheweb/muse/issues/404.

@Hellysonrp would appreciate if you tried this out. Still need to look into implementing bucketing but it's otherwise complete. A few notes:
- This will initially delete all cached files, so I recommend not pointing it to your production cache directory
- I removed the `-re` option (see https://github.com/codetheweb/muse/issues/389), see commit message: f5149dfaba64c62f0a9ea6deab600b3d4d9b0f39. I was never able to reproduce the problem in the linked issue, could you see if that regresses? I suspect it may have been fixed by Discord.js v13 / @discordjs/voice.

### CODE REVIEW

**Comment by Hellysonrp** [comment]
I'll try it out.
Allow me to test it throughout the next week, just to be sure everything is working.

**Comment by Hellysonrp** [comment]
Today the bot died after playing a music, apparently it tried to write to a nonexistent cache file:
Screenshot_22

I don't know how this happened.
Maybe somehow it tried to move the file while it was being written to? There is a file with the same hash outside of the temp folder.
I spoke with the person that was using the bot at the time this happened, and apparently this song was skipped from the playlist (probably due to an '403' error from the YouTube API, it happens a lot, didn't find it in the logs though), they added the song again, the song played fine but after that the bot died.

That's the only problem so far.

**Comment by codetheweb** [comment]
I wasn't able to reproduce that, but I changed the event listener on the writable stream from `finish` to `close` which might help with possible race conditions.

Did you notice anything for 
> I removed the -re option (see Bot randomly stops streaming audio #389), see commit message: f5149df. I was never able to reproduce the problem in the linked issue, could you see if that regresses? I suspect it may have been fixed by Discord.js v13 / @discordjs/voice.

?

**Comment by Hellysonrp** [comment]
So far, no problems related to the `-re` option.
It's worth to mention that the original issue was:

> repeatable for long (50 minutes) videos, though has occasionally happened on much shorter videos as well

I didn't test the bot with long videos yet, I'll try to do that today.
But it might be worth to add the `-re` option when `shouldCacheVideo` is false. It wouldn't break the cache, because the video wouldn't be cached, and would certainly prevent any issues with long videos.

**Comment by codetheweb** [comment]
> Since long videos aren't cached, it might be worth to add the -re option when shouldCacheVideo is false. It wouldn't break the cache, because the video wouldn't be cached, and would certainly prevent any issues with long videos.

Good point, I added it back in for uncached streams.

**Comment by Hellysonrp** [comment]
Everything is working as expected.
I think it's safe to merge the PR.

**Comment by codetheweb** [comment]
Sounds good.

I did notice the same crash that you posted happened once to me, but tracing through the logic I'm not sure where it could be occurring. If we can figure out a reproducible test case I'll fix that later.

**Comment by codetheweb** [comment]
Thanks for testing.

**Pull request merged**
