### PR TITLE
Switch from node-ytsr to Distube's fork

### LINKED ISSUE #1000: node-ytsr deprecated and broken for certain inputs
/home/container/node_modules/ytsr/lib/parseItem.js:415
    rawItems = (obj.content.verticalListRenderer || obj.content.horizontalMovieListRenderer).items;
                                                                                             ^
TypeError: Cannot read properties of undefined (reading 'items')
    at parseShelf (/home/container/node_modules/ytsr/lib/parseItem.js:415:94)
    at parseItem (/home/container/node_modules/ytsr/lib/parseItem.js:32:14)
    at catchAndLogFunc (/home/container/node_modules/ytsr/lib/parseItem.js:90:12)
    at module.exports (/home/container/node_modules/ytsr/lib/parseItem.js:119:46)
    at <anonymous> (/home/container/node_modules/ytsr/lib/main.js:53:34)
    at Array.map (<anonymous>)
    at module.exports (/home/container/node_modules/ytsr/lib/main.js:53:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at KeyValueCacheProvider.wrap (/home/container/src/services/key-value-cache.ts:53:20)
/********************************************************************************************************************************************************************************************************
failed at func parseItem: Cannot read properties of undefined (reading 'items')
pls post the the files in /home/container/node_modules/ytsr/dumps to https://github.com/TimeForANinja/node-ytsr/issues
os: linux-x64, node.js: v16.20.2, ytsr: 3.8.4
********************************************************************************************************************************************************************************************************\
/home/container/node_modules/ytsr/lib/parseItem.js:415
    rawItems = (obj.content.verticalListRenderer || obj.content.horizontalMovieListRenderer).items;
                                                                                             ^
TypeError: Cannot read properties of undefined (reading 'items')
    at parseShelf (/home/container/node_modules/ytsr/lib/parseItem.js:415:94)
    at parseItem (/home/container/node_modules/ytsr/lib/parseItem.js:32:14)
    at catchAndLogFunc (/home/container/node_modules/ytsr/lib/parseItem.js:90:12)
    at module.exports (/home/container/node_modules/ytsr/lib/parseItem.js:119:46)
    at <anonymous> (/home/container/node_modules/ytsr/lib/main.js:53:34)
    at Array.map (<anonymous>)
    at module.exports (/home/container/node_modules/ytsr/lib/main.js:53:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at KeyValueCacheProvider.wrap (/home/container/src/services/key-value-cache.ts:53:20)
/********************************************************************************************************************************************************************************************************
failed at func parseItem: Cannot read properties of undefined (reading 'items')
pls post the the files in /home/container/node_modules/ytsr/dumps to https://github.com/TimeForANinja/node-ytsr/issues
os: linux-x64, node.js: v16.20.2, ytsr: 3.8.4
********************************************************************************************************************************************************************************************************\

### PR DESCRIPTION
**Pull request by sonroyaalmerol**
Closes #1000 

Tried dropping in the ytsr fork as a direct replacement to the deprecated node-ytsr. Seems to work perfectly fine when I tested locally.

The "biggest" change here would be the modification of the minimum Node version requirement to 18 as the fork dropped version 16. I assume it would be fine as the Dockerfile use version 18 anyways.

### CODE REVIEW

**Comment by EugeneLeclerc** [comment]
Any news on this? node-ytsr is still broken, it would be nice to have this merged.

**Comment by codetheweb** [comment]
I somehow didn't see this in April, sorry. I ended up merging https://github.com/codetheweb/muse/pull/1042 instead.

**Comment by codetheweb** [comment]
My bad, got dependencies mixed up, this is still useful and appreciated :)

**Comment by EugeneLeclerc** [comment]
Thanks!

**Pull request merged**
