### PR TITLE
Announce current song

### LINKED ISSUE #342: Add an option to announce current song
Add an option to announce the current song to be messaged on the channel that is being monitered.

### PR DESCRIPTION
**Pull request by bokherus**
Closes #342 

**Changes**

- Send an embeded message to announce current playing song.

**Demo**

image

- [ ] I updated the changelog

### CODE REVIEW

**Comment by bokherus** [comment]
@codetheweb I think there might be something wrong with release for pull request it doesn't pick up the new changes.

**Comment by codetheweb** [comment]
Looks like it's working for me. The comment has the correct latest commit hash;.

**Comment by codetheweb** [comment]
I made some tweaks so that basically the response is the same as the queue embed without the upcoming tracks. Please try it out and let me know what you think, feels pretty good to me.

**Comment by bokherus** [comment]
That's a great idea! - I love the consistency in the design. There're some issues that need to be address if we are going with this style. In the screenshot below you can see one issue is that the message is no longer valid for `queue` command once the bot disconnects. The queue command embed title will need to updated based on state of the player. 

image

Another issue is the track elapsed time, I feel that it's cool but functionality wise it's not so useful because play embed would mostly show as `00:00/song duration` and the buttons cannot be clicked. 

### Suggestion for enhancements
 I think would be nice is to have color that further enhance the intent of the message (maybe green of playing, red for disconnected or paused) for embed message. Also, now that we have requested user, I think it would be also nice to add song duration and requested by to every song in the queue. Please see examples below.
 
 Note: I would recommend discord's detect voice green circle on user avatar more than green in the example below as it's more intuitive


image
image

**Comment by bokherus** [comment]
I've made some tweak based on your idea, fixed some issue that I've mentioned above and some refactoring. Please let me know what you think about it. I would be happy to reiterate this until we both find that it provides the best user experience.

**Comment by bokherus** [comment]
### Snapshots of the queue command UI in different state
1. Currently playing
Screen Shot 2565-01-18 at 23 41 37

2. Disconnected or paused
Screen Shot 2565-01-18 at 23 42 09

**Comment by codetheweb** [comment]
I'm really liking this! Feels super clean and intuitive.

My main comment for the UI so far is that sometimes it can feel a little awkward if the track name is too long and the duration wraps onto a new line:
Screen Shot 2022-01-19 at 7 40 27 PM

Maybe we want to set a max line length and format the lines like
> `11.` Virtual Riot - In My Head ft. PRXZM... `[03:42]`

?

> Note: I would recommend discord's detect voice green circle on user avatar more than green in the example below as it's more intuitive

What do you mean by this?

**Comment by bokherus** [comment]
> Maybe we want to set a max line length and format the lines like

Yeah that definitely should be truncated. I'll experiment with max number of characters and maybe some algorithm or regex to remove stuff in brackets () [] since they seem to be additional details. Those details could be important in some cases, what do you think about this, for the first iteration I think let's just go with a fixed max number of character.


> > Note: I would recommend discord's detect voice green circle on user avatar more than green in the example below as it's more intuitive
> 
> What do you mean by this?

Green color usually indicates positive or active state in user interfaces. So for queue command, if it's playing then the title will be "Now Playing" and show as green, if the bot is disconnected (not playing) it will show "Queued songs" with greyish color to indicate inactive state

green hint
green hint 2
image

**Comment by bokherus** [comment]
I'm using different max value for ascii and non-ascii characters. Languages like Chinese, Japanese, Korean have large block characters that could take up space equivalent to 2 english characters.

**Comment by codetheweb** [comment]
> Green color usually indicates positive or active state in user interfaces. So for queue command, if it's playing then the title will be "Now Playing" and shown in green, if the bot is disconnected (not playing) it will show "Queued songs" with greyish color to indicate inactive state

Ah, I thought you were talking about something else but yes that makes sense.

> I'm using different max value for ascii and non-ascii characters. Languages like Chinese, Japanese, Korean have large block characters that could take up space equivalent to 2-3 english characters.

Makes sense 👍.

Made a few tweaks; if everything looks good to you we can merge & release. :)

**Comment by bokherus** [comment]
Looks awesome! I made final tweak on the display of total length and queue size for 0 and 1 song in queue cases. I would be happy for this to be merged and release. Thanks for your constant support that help shaped this PR and for maintaining this cool bot :)

**Comment by codetheweb** [comment]
Released in [v0.5.0](https://github.com/codetheweb/muse/releases/tag/v0.5.0).

**Pull request merged**
