### PR TITLE
Configurable voice channel leave behavior

### PR DESCRIPTION
**Pull request by Xenomer**
Adds two features mentioned in #513 and #481:
- configurable idle waiting time before leaving when queue empties (or don't leave at all)
- setting that allows you to *not* leave the VC when everyone else leaves.

Not sure about the descriptions and approach and stuff so always open to suggestions :D

Also, the default idling time before auto-disconnecting is now 30s, and the previous insta-leave is impossible (since 0 seconds disables the autoleave completely, though setting something like 1s gives mostly the same behavior)

### CODE REVIEW

**Comment by codetheweb** [comment]
Thanks for the contributions!

I'm not sure how you were able to get this to run though without creating database migrations. In any case, added them in be35378.

**Comment by Xenomer** [comment]
Hmm, it seems committing through vscode skipped linting altogether and it's not going through now that I'm trying to sign the commits lol. Also not sure if github will agree with me if I rewrite history a little in my fork and sign the previous commits or if we need to redo the whole PR.

**Comment by codetheweb** [comment]
It's fine, just be sure to sign your commits in any future PRs. 😃

**Comment by codetheweb** [comment]
Released in [v1.1.0](https://github.com/codetheweb/muse/releases/tag/v1.1.0).

**Pull request merged**
