### PR TITLE
fix command permission handling and push discord to v10

### LINKED ISSUE #637: DiscordAPIError: 405: Method Not Allowed | Crashes While Bot is Invited to Any Server
**What's happening?**
Crashes immediately after inviting to a server.
Tested changing permission integer to 8 (Administrator) out of curiosity but no change.
Have invited it to two servers. One I am the owner of, the other I just have manage server permissions. Only invited the bot to the server I own as Administrator.
Each subsequent attempt to run the bot while it is in any guild will crash until the bot is kicked from all servers.
Appears to crash while processing permissions.

**Logs**

```
✔ Database migrations applied.
✔ Ready! Invite the bot with https://discordapp.com/oauth2/authorize?client_id=<censored>&scope=bot%20applications.commands&permissions=36700288
/root/muse/node_modules/discord.js/src/rest/RequestHandler.js:350
      throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: 405: Method Not Allowed
    at RequestHandler.execute (/root/muse/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/root/muse/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async ApplicationCommandPermissionsManager.set (/root/muse/node_modules/discord.js/src/managers/ApplicationCommandPermissionsManager.js:186:18)
    at async updatePermissionsForGuild (file:///root/muse/src/utils/update-permissions-for-guild.ts:32:3)
    at async Client.guild_create_default (file:///root/muse/src/events/guild-create.ts:36:3) {
  method: 'put',
  path: '/applications/968996889099911238/guilds/450306155361861632/commands/permissions',
  code: 0,
  httpStatus: 405,
  requestData: {
    json: [
      {
        id: '968999097581322281',
        permissions: [
          { id: '148334523514486784', permission: true, type: 2 },
          { id: '450306155361861632', permission: false, type: 1 },
          { id: '148334523514486784', permission: true, type: 2 }
        ]
      },
      {
        id: '968999097581322282',
        permissions: [
          { id: '148334523514486784', permission: true, type: 2 },
          { id: '450306155361861632', permission: false, type: 1 },
          { id: '148334523514486784', permission: true, type: 2 }
        ]
      },
      {
        id: '968999097581322283',
        permissions: [
          { id: '148334523514486784', permission: true, type: 2 },
          { id: '450306155361861632', permission: false, type: 1 },
          { id: '148334523514486784', permission: true, type: 2 }
        ]
      },
      {
        id: '968999097581322284',
        permissions: [
          { id: '148334523514486784', permission: true, type: 2 },
          { id: '450306155361861632', permission: false, type: 1 },
          { id: '148334523514486784', permission: true, type: 2 }
        ]
      },
      {
        id: '968999097581322285',
        permissions: [
          { id: '148334523514486784', permission: true, type: 2 },
          { id: '450306155361861632', permission: false, type: 1 },
          { id: '148334523514486784', permission: true, type: 2 }
        ]
      },
      {
        id: '968999097581322286',
        permissions: [
          { id: '148334523514486784', permission: true, type: 2 },
          { id: '450306155361861632', permission: false, type: 1 },
          { id: '148334523514486784', permission: true, type: 2 }
        ]
      },
      {
        id: '968999097581322287',
        permissions: [
          { id: '148334523514486784', permission: true, type: 2 },
          { id: '450306155361861632', permission: false, type: 1 },
          { id: '148334523514486784', permission: true, type: 2 }
        ]
      },
      {
        id: '968999097581322288',
        permissions: [
          { id: '148334523514486784', permission: true, type: 2 },
          { id: '450306155361861632', permission: false, type: 1 },
          { id: '148334523514486784', permission: true, type: 2 }
        ]
      },
      {
        id: '968999097581322289',
        permissions: [
          { id: '148334523514486784', permission: true, type: 2 },
          { id: '450306155361861632', permission: false, type: 1 },
          { id: '148334523514486784', permission: true, type: 2 }
        ]
      },
      {
        id: '968999097581322290',
        permissions: [
          { id: '148334523514486784', permission: true, type: 2 },
          { id: '450306155361861632', permission: false, type: 1 },
          { id: '148334523514486784', permission: true, type: 2 }
        ]
      },
      {
        id: '968999097652637696',
        permissions: [
          { id: '148334523514486784', permission: true, type: 2 },
          { id: '450306155361861632', permission: false, type: 1 },
          { id: '148334523514486784', permission: true, type: 2 }
        ]
      },
      {
        id: '968999097652637697',
        permissions: [
          { id: '148334523514486784', permission: true, type: 2 },
          { id: '450306155361861632', permission: false, type: 1 },
          { id: '148334523514486784', permission: true, type: 2 }
        ]
      },
      {
        id: '968999097652637698',
        permissions: [
          { id: '148334523514486784', permission: true, type: 2 },
          { id: '450306155361861632', permission: false, type: 1 },
          { id: '148334523514486784', permission: true, type: 2 }
        ]
      },
      {
        id: '968999097652637699',
        permissions: [
          { id: '148334523514486784', permission: true, type: 2 },
          { id: '450306155361861632', permission: false, type: 1 },
          { id: '148334523514486784', permission: true, type: 2 }
        ]
      },
      {
        id: '968999097652637700',
        permissions: [
          { id: '148334523514486784', permission: true, type: 2 },
          { id: '450306155361861632', permission: false, type: 1 },
          { id: '148334523514486784', permission: true, type: 2 }
        ]
      },
      {
        id: '968999097652637701',
        permissions: [
          { id: '148334523514486784', permission: true, type: 2 },
          { id: '450306155361861632', permission: false, type: 1 },
          { id: '148334523514486784', permission: true, type: 2 }
        ]
      },
      {
        id: '968999097652637702',
        permissions: [
          { id: '148334523514486784', permission: true, type: 2 },
          { id: '450306155361861632', permission: false, type: 1 },
          { id: '148334523514486784', permission: true, type: 2 }
        ]
      },
      {
        id: '968999097652637703',
        permissions: [
          { id: '148334523514486784', permission: true, type: 2 },
          { id: '450306155361861632', permission: false, type: 1 },
          { id: '148334523514486784', permission: true, type: 2 }
        ]
      }
    ],
    files: []
  }
}
file:///root/muse/node_modules/execa/lib/error.js:59
                error = new Error(message);
                        ^

Error: Command failed with exit code 1: esmo src/scripts/migrate-and-start.ts
    at makeError (file:///root/muse/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///root/muse/node_modules/execa/index.js:119:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///root/muse/src/scripts/run-with-database-url.ts:5:3 {
  shortMessage: 'Command failed with exit code 1: esmo src/scripts/migrate-and-start.ts',
  command: 'esmo src/scripts/migrate-and-start.ts',
  escapedCommand: 'esmo "src/scripts/migrate-and-start.ts"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

```

**Screenshots**
N/A

**Additional context**
Fresh install of v1.9.0 branch.
Installed using command `npm i`.
Run using command `npm run start`.

**Runtime**
I'm running Muse:
- [x] Directly from the cloned repository
- [ ] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: 1.9.0
- Docker (if applicable): N/A
- OS: Ubuntu Server 16.04 LTS

### PR DESCRIPTION
**Pull request by kkendzia**
So I changed a lot and the bot probably needs those 2 new env vars to make it work properly. I missed a lot of documentation as far as I can tell, but for now it works the way I did it. Maybe you can take it as inspiration to fix it in a better way :)

fixes #637 637

### CODE REVIEW

**Comment by kkendzia** [comment]
Well, worked somehow for some minutes - now it's failing again... I'm lost.

**Comment by h45h74x** [comment]
Hi, just testing this out right now :D
Don't forget to update the `.env.example` file as well

**Comment by kkendzia** [comment]
Thx for the hints! Will work on it tomorrow again

**Comment by h45h74x** [comment]
> Thx for the hints! Will work on it tomorrow again

Thx for your great work!

Whilst I have problems with playing from YouTube, I found out that muse [supports HTTP streams](https://github.com/codetheweb/muse/releases/tag/v1.4.0). The bot is working quite nicely, as you can see:
image

**Comment by codetheweb** [comment]
I apologize for the late review.

This looks great, thank you for your help. The main issue I have with this though is that startup time is greatly increased, which makes development with hot reloading quite painful. The work migrating to v10 is much appreciated, but I think I'll wait on this until https://github.com/discordjs/discord.js/pull/7861 is merged and then we can sidestep having to change command permissions by just setting default permissions when creating the commands.

**Comment by codetheweb** [comment]
Also, the QoL improvement where it recreates settings for a guild instead of throwing is much appreciated. :)

**Comment by febluthn** [comment]
Hey guys, it seems https://github.com/discordjs/discord.js/pull/7861
is merged. Could you please have a look again?

**Comment by codetheweb** [comment]
Already on the list to do tonight :)

**Comment by kkendzia** [comment]
Sorry I don't have time today - try to get it integrated tomorrow. Otherwise of course @codetheweb feel free to implement it by yourself :)

**Review by codetheweb — APPROVED** [review]

**Pull request merged**
