### PR TITLE
Normalize playback volume across tracks

### PR DESCRIPTION
**Pull request by codetheweb**

### CODE REVIEW

**Comment by UniversalSuperBox** [comment]
This is really excellent! It tones down some of the loudest tracks on YouTube to a very acceptable volume -- https://www.youtube.com/watch?v=agCiXI8kZjE usually gets played at **38%** of its input volume in the web interface, it was quite a scorcher!

It's still possible to get a playlist full of mixed relative loudness with this (there's a lot of music on YouTube that is lower than their set loudness). However, once someone sets Muse at a volume that matches their comfort level for a track loud enough for YouTube to turn it down, Muse won't generally go above that again.

In my research on YouTube's loudness profiling, I found a lot of peer recommendations to creators to master their tracks very loud since YT won't turn up quiet tracks. That explains how we got in this situation in the first place.

Anyway, to my knowledge, Muse will be the only easily self-hostable music bot with this feature ^-^

**Comment by UniversalSuperBox** [comment]
Ah, forgot one thing. Is there any music that doesn't have a loudness profile? Maybe things that were uploaded pre-2015 when they started profiling? Was that applied retroactively?

**Comment by codetheweb** [comment]
> It's still possible to get a playlist full of mixed relative loudness with this (there's a lot of music on YouTube that is lower than their set loudness). However, once someone sets Muse at a volume that matches their comfort level for a track loud enough for YouTube to turn it down, Muse won't generally go above that again.

Whoops, I had a typo in the initial commit, fixed in [65a7861](https://github.com/codetheweb/muse/pull/939/commits/65a7861f374d98080cd27b7061c75285f03eeeb3)--sorry about that, the behavior should be correct now.

Muse both boosts quiet tracks and decreases loud ones, unlike the YouTube player which only decreases loud ones (I think?).

> Ah, forgot one thing. Is there any music that doesn't have a loudness profile? Maybe things that were uploaded pre-2015 when they started profiling? Was that applied retroactively?

I wasn't able to find any documentation on it but based on my testing, it does seem like they retroactively processed audio tracks.

**Comment by UniversalSuperBox** [comment]
Cool. Amplifying quiet tracks is a nice touch, even if YouTube shies away from it. Could cause some distortion, but I'm not sure how much it matters over Gamer Voice Chat. At least we aren't using Speex I guess.

> it does seem like they retroactively processed audio tracks

Even better!

I tried it with a stream and it just played at default volume too. Very nice.

**Pull request merged**
