### PR TITLE
Fix Prisma path on Windows?

### LINKED ISSUE #475: npm start error
```
PS D:\Files\Muse> npm run start

> muse@0.3.1 start
> npm run env:set-database-url -- node --experimental-json-modules dist/src/scripts/migrate-and-start.js


> muse@0.3.1 env:set-database-url
> node dist/src/scripts/run-with-database-url.js "node" "--experimental-json-modules" "dist/src/scripts/migrate-and-start.js"

node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_IMPORT_ASSERTION_TYPE_MISSING]: Module "file:///D:/Files/Muse/dist/package.json" needs an import assertion of type "json"
    at new NodeError (node:internal/errors:371:5)
    at validateAssertions (node:internal/modules/esm/assert:82:15)
    at defaultLoad (node:internal/modules/esm/load:25:3)
    at ESMLoader.load (node:internal/modules/esm/loader:359:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:280:58)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:297:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:261:34)
    at async ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:81:21)
    at async Promise.all (index 1) {
  code: 'ERR_IMPORT_ASSERTION_TYPE_MISSING'
}

Node.js v17.3.1
file:///D:/Files/Muse/node_modules/execa/lib/error.js:59
                error = new Error(message);
                        ^

Error: Command failed with exit code 1: node --experimental-json-modules dist/src/scripts/migrate-and-start.js
    at makeError (file:///D:/Files/Muse/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///D:/Files/Muse/node_modules/execa/index.js:119:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///D:/Files/Muse/dist/src/scripts/run-with-database-url.js:6:5 {
  shortMessage: 'Command failed with exit code 1: node --experimental-json-modules dist/src/scripts/migrate-and-start.js',
  command: 'node --experimental-json-modules dist/src/scripts/migrate-and-start.js',
  escapedCommand: 'node --experimental-json-modules "dist/src/scripts/migrate-and-start.js"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v17.3.1
```
I'm having this error when starting the bot on windows

### PR DESCRIPTION
**Pull request by codetheweb**
Closes #475.

- [x] I updated the changelog

@lemns can you please try this out and see if it fixes the issue? I can't easily test on Windows.

### CODE REVIEW

**Comment by lemns** [comment]
Looks like it didn't work, if I tested it right. 

I was really dumb and couldnt figure out how to test this PR with git, so I just edited the file you edited manually (create-database-url.ts) by copying its contents :d

```
PS D:\MUSIC\MUSE\muse> npm run start

> muse@0.5.3 start
> npm run env:set-database-url -- node --experimental-json-modules dist/src/scripts/migrate-and-start.js


> muse@0.5.3 env:set-database-url
> node dist/src/scripts/run-with-database-url.js "node" "--experimental-json-modules" "dist/src/scripts/migrate-and-start.js"

(node:14596) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
========================================
========================================
================= muse =================
========================================
=========== Made with 🎶 by ============
==== https://github.com/codetheweb =====
========================================
========================================

Running version 0.5.3 built on unknown date (commit unknown)

🔧 Need help? https://github.com/codetheweb/muse/discussions/new
🐛 Bug? https://github.com/codetheweb/muse/issues/new
✨ New feature? https://github.com/codetheweb/muse/issues/new
☕ Discussion? https://github.com/codetheweb/muse/discussions/new
💰 Help me? https://www.paypal.me/codetheweb https://github.com/sponsors/codetheweb


✖ Failed to apply database migrations:
Error: P1012: error: Error validating: This line is not a valid definition within a datasource.
  -->  schema.prisma:4
   |
 3 |                 provider = "sqlite"
 4 |                 url = "file:D:\MUSIC\MUSE\muse\data\db.sqlite"
 5 |             }
   |

file:///D:/MUSIC/MUSE/muse/node_modules/execa/lib/error.js:59
                error = new Error(message);
                        ^

Error: Command failed with exit code 1: node --experimental-json-modules dist/src/scripts/migrate-and-start.js
    at makeError (file:///D:/MUSIC/MUSE/muse/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///D:/MUSIC/MUSE/muse/node_modules/execa/index.js:119:26)
    at async file:///D:/MUSIC/MUSE/muse/dist/src/scripts/run-with-database-url.js:6:5 {
  shortMessage: 'Command failed with exit code 1: node --experimental-json-modules dist/src/scripts/migrate-and-start.js',  command: 'node --experimental-json-modules dist/src/scripts/migrate-and-start.js',
  escapedCommand: 'node --experimental-json-modules "dist/src/scripts/migrate-and-start.js"',    
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Comment by lemns** [comment]
I couldnt figure out how to test it with git, so I just manually edited the file, hope I didn't miss any steps

**Comment by lemns** [comment]
Nevermind my older messages, it did work for me.

**Comment by codetheweb** [comment]
Fantastic!

I was kinda shooting in the dark so glad it worked. :)

**Comment by codetheweb** [comment]
Released in v0.5.4.

**Pull request merged**
